# Generated by Django 5.2.7 on 2025-10-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='bord',
            new_name='board',
        ),
    ]
